# E-Commerce Returns Prediction using the Kaggle Data
Here, I have got some synthetic data from the Kaggle.com and am currently using it to predict the *Return Status* of the product bought by the customer.<br><br>
Loading the data.

In [180]:
import pandas as pd

df = pd.read_csv("/content/ecommerce_returns_synthetic_data.csv")
df.head(5)

,Order_ID,Product_ID,User_ID,Order_Date,Return_Date,Product_Category,Product_Price,Order_Quantity,Return_Reason,Return_Status,Days_to_Return,User_Age,User_Gender,User_Location,Payment_Method,Shipping_Method,Discount_Applied
0,ORD00000000,PROD00000000,USER00000000,2023-08-05,2024-08-26,Clothing,411.59,3,Changed mind,Returned,387.0,58,Male,City54,Debit Card,Next-Day,45.27
1,ORD00000001,PROD00000001,USER00000001,2023-10-09,2023-11-09,Books,288.88,3,Wrong item,Returned,31.0,68,Female,City85,Credit Card,Express,47.79
2,ORD00000002,PROD00000002,USER00000002,2023-05-06,NaN,Toys,390.03,5,NaN,Not Returned,NaN,22,Female,City30,Debit Card,Next-Day,26.64
3,ORD00000003,PROD00000003,USER00000003,2024-08-29,NaN,Toys,401.09,3,NaN,Not Returned,NaN,40,Male,City95,PayPal,Next-Day,15.37
4,ORD00000004,PROD00000004,USER00000004,2023-01-16,NaN,Books,110.09,4,NaN,Not Returned,NaN,34,Female,City80,Gift Card,Standard,16.37

In [181]:
df.describe()

,Product_Price,Order_Quantity,Days_to_Return,User_Age,Discount_Applied
count,10000.000000,10000.000000,5052.000000,10000.000000,10000.000000
mean,252.369307,3.006100,1.453682,44.195000,24.992162
std,142.883865,1.406791,297.983208,15.311983,14.363396
min,5.010000,1.000000,-719.000000,18.000000,0.000000
25%,128.650000,2.000000,-214.000000,31.000000,12.752500
50%,250.445000,3.000000,1.000000,44.000000,24.840000
75%,377.837500,4.000000,218.000000,57.000000,37.605000
max,499.890000,5.000000,726.000000,70.000000,50.000000

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10000 non-null  object
 1   Product_ID        10000 non-null  object
 2   User_ID           10000 non-null  object
 3   Order_Date        10000 non-null  object
 4   Return_Date       5052 non-null   object
 5   Product_Category  10000 non-null  object
 6   Product_Price     10000 non-null  float64
 7   Order_Quantity    10000 non-null  int64
 8   Return_Reason     5052 non-null   object
 9   Return_Status     10000 non-null  object
 10  Days_to_Return    5052 non-null   float64
 11  User_Age          10000 non-null  int64
 12  User_Gender       10000 non-null  object
 13  User_Location     10000 non-null  object
 14  Payment_Method    10000 non-null  object
 15  Shipping_Method   10000 non-null  object
 16  Discount_Applied  10000 non-null  float64
dtypes: float64(3), int64(2), object(12)
memory usage: 1.3+ MB

In [183]:
list(df.columns)

['Order_ID',
 'Product_ID',
 'User_ID',
 'Order_Date',
 'Return_Date',
 'Product_Category',
 'Product_Price',
 'Order_Quantity',
 'Return_Reason',
 'Return_Status',
 'Days_to_Return',
 'User_Age',
 'User_Gender',
 'User_Location',
 'Payment_Method',
 'Shipping_Method',
 'Discount_Applied']

Based on the above understanding, we can remove the following columns/features as they doesn't seems to be that much infomative.
- Order_ID
- Product_ID
- User_ID
- Order_Date
- Return_Date
- Return_Reason (Might keep it by playing around during the encoding)
- User_Location
- Shipping_Method (Need to study this)

In [184]:
df.drop(["Order_ID", "Product_ID", "User_ID", "Order_Date", "Return_Date", "User_Location"], axis=1, inplace=True)
list(df.columns)

['Product_Category',
 'Product_Price',
 'Order_Quantity',
 'Return_Reason',
 'Return_Status',
 'Days_to_Return',
 'User_Age',
 'User_Gender',
 'Payment_Method',
 'Shipping_Method',
 'Discount_Applied']

In [185]:
df.describe()

,Product_Price,Order_Quantity,Days_to_Return,User_Age,Discount_Applied
count,10000.000000,10000.000000,5052.000000,10000.000000,10000.000000
mean,252.369307,3.006100,1.453682,44.195000,24.992162
std,142.883865,1.406791,297.983208,15.311983,14.363396
min,5.010000,1.000000,-719.000000,18.000000,0.000000
25%,128.650000,2.000000,-214.000000,31.000000,12.752500
50%,250.445000,3.000000,1.000000,44.000000,24.840000
75%,377.837500,4.000000,218.000000,57.000000,37.605000
max,499.890000,5.000000,726.000000,70.000000,50.000000

In [186]:
df.head(5)

,Product_Category,Product_Price,Order_Quantity,Return_Reason,Return_Status,Days_to_Return,User_Age,User_Gender,Payment_Method,Shipping_Method,Discount_Applied
0,Clothing,411.59,3,Changed mind,Returned,387.0,58,Male,Debit Card,Next-Day,45.27
1,Books,288.88,3,Wrong item,Returned,31.0,68,Female,Credit Card,Express,47.79
2,Toys,390.03,5,NaN,Not Returned,NaN,22,Female,Debit Card,Next-Day,26.64
3,Toys,401.09,3,NaN,Not Returned,NaN,40,Male,PayPal,Next-Day,15.37
4,Books,110.09,4,NaN,Not Returned,NaN,34,Female,Gift Card,Standard,16.37

Counting the number of labels in the dataset.

In [187]:
df["Return_Status"].value_counts()

Return_Status
Returned        5052
Not Returned    4948
Name: count, dtype: int64

Amazing! almost balanced. But, since the dataset is the synthetic one from the Kaggle.com, we shall consider for the conceptual purposes only.

In [188]:
df["Product_Category"].value_counts()

Product_Category
Books          2041
Home           2030
Clothing       2000
Electronics    1985
Toys           1944
Name: count, dtype: int64

Let's perform *Label Encoding* on column `Product_Category`.<br>
Fine, Label Encoding is not optimal for this task. It prioritize the ones with the higher numerical value, we shall go for the *One-hot Encoding*.

In [189]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [190]:
encoded = encoder.fit_transform(df[["Product_Category"]]).toarray()
encoded

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [191]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoder_df

,Product_Category_Books,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Product_Category_Toys
0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...
9995,0.0,0.0,0.0,1.0,0.0
9996,0.0,0.0,1.0,0.0,0.0
9997,0.0,0.0,0.0,0.0,1.0
9998,0.0,0.0,0.0,0.0,1.0
9999,0.0,0.0,0.0,0.0,1.0

In [192]:
df = pd.concat([df, encoder_df], axis=1)

In [193]:
df.head()

,Product_Category,Product_Price,Order_Quantity,Return_Reason,Return_Status,Days_to_Return,User_Age,User_Gender,Payment_Method,Shipping_Method,Discount_Applied,Product_Category_Books,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Product_Category_Toys
0,Clothing,411.59,3,Changed mind,Returned,387.0,58,Male,Debit Card,Next-Day,45.27,0.0,1.0,0.0,0.0,0.0
1,Books,288.88,3,Wrong item,Returned,31.0,68,Female,Credit Card,Express,47.79,1.0,0.0,0.0,0.0,0.0
2,Toys,390.03,5,NaN,Not Returned,NaN,22,Female,Debit Card,Next-Day,26.64,0.0,0.0,0.0,0.0,1.0
3,Toys,401.09,3,NaN,Not Returned,NaN,40,Male,PayPal,Next-Day,15.37,0.0,0.0,0.0,0.0,1.0
4,Books,110.09,4,NaN,Not Returned,NaN,34,Female,Gift Card,Standard,16.37,1.0,0.0,0.0,0.0,0.0

In [194]:
df.drop(["Product_Category"], axis=1, inplace=True)
df.head(5)

,Product_Price,Order_Quantity,Return_Reason,Return_Status,Days_to_Return,User_Age,User_Gender,Payment_Method,Shipping_Method,Discount_Applied,Product_Category_Books,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Product_Category_Toys
0,411.59,3,Changed mind,Returned,387.0,58,Male,Debit Card,Next-Day,45.27,0.0,1.0,0.0,0.0,0.0
1,288.88,3,Wrong item,Returned,31.0,68,Female,Credit Card,Express,47.79,1.0,0.0,0.0,0.0,0.0
2,390.03,5,NaN,Not Returned,NaN,22,Female,Debit Card,Next-Day,26.64,0.0,0.0,0.0,0.0,1.0
3,401.09,3,NaN,Not Returned,NaN,40,Male,PayPal,Next-Day,15.37,0.0,0.0,0.0,0.0,1.0
4,110.09,4,NaN,Not Returned,NaN,34,Female,Gift Card,Standard,16.37,1.0,0.0,0.0,0.0,0.0

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Product_Price                 10000 non-null  float64
 1   Order_Quantity                10000 non-null  int64
 2   Return_Reason                 5052 non-null   object
 3   Return_Status                 10000 non-null  object
 4   Days_to_Return                5052 non-null   float64
 5   User_Age                      10000 non-null  int64
 6   User_Gender                   10000 non-null  object
 7   Payment_Method                10000 non-null  object
 8   Shipping_Method               10000 non-null  object
 9   Discount_Applied              10000 non-null  float64
 10  Product_Category_Books        10000 non-null  float64
 11  Product_Category_Clothing     10000 non-null  float64
 12  Product_Category_Electronics  10000 non-null  float64
 13  Product_Category_Home         10000 non-null  float64
 14  Product_Category_Toys         10000 non-null  float64
dtypes: float64(8), int64(2), object(5)
memory usage: 1.1+ MB

Honestly, when it comes to the Machine Learning Models. We must not be Gender Biased, Age can be factor affecting the return of the products.

In [196]:
df.drop(["User_Gender"], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Product_Price                 10000 non-null  float64
 1   Order_Quantity                10000 non-null  int64
 2   Return_Reason                 5052 non-null   object
 3   Return_Status                 10000 non-null  object
 4   Days_to_Return                5052 non-null   float64
 5   User_Age                      10000 non-null  int64
 6   Payment_Method                10000 non-null  object
 7   Shipping_Method               10000 non-null  object
 8   Discount_Applied              10000 non-null  float64
 9   Product_Category_Books        10000 non-null  float64
 10  Product_Category_Clothing     10000 non-null  float64
 11  Product_Category_Electronics  10000 non-null  float64
 12  Product_Category_Home         10000 non-null  float64
 13  Product_Category_Toys         10000 non-null  float64
dtypes: float64(8), int64(2), object(4)
memory usage: 1.1+ MB

In [197]:
df["Return_Status"].value_counts()

Return_Status
Returned        5052
Not Returned    4948
Name: count, dtype: int64

In [198]:
df['Return_Status'] = df['Return_Status'].map({"Returned": 1, "Not Returned": 0}).astype(int)
df['Return_Status'].head(5)

0    1
1    1
2    0
3    0
4    0
Name: Return_Status, dtype: int64

In [199]:
df['Return_Status'].isnull().sum().item()

0

In [200]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Product_Price                 10000 non-null  float64
 1   Order_Quantity                10000 non-null  int64
 2   Return_Reason                 5052 non-null   object
 3   Return_Status                 10000 non-null  int64
 4   Days_to_Return                5052 non-null   float64
 5   User_Age                      10000 non-null  int64
 6   Payment_Method                10000 non-null  object
 7   Shipping_Method               10000 non-null  object
 8   Discount_Applied              10000 non-null  float64
 9   Product_Category_Books        10000 non-null  float64
 10  Product_Category_Clothing     10000 non-null  float64
 11  Product_Category_Electronics  10000 non-null  float64
 12  Product_Category_Home         10000 non-null  float64
 13  Product_Category_Toys         10000 non-null  float64
dtypes: float64(8), int64(3), object(3)
memory usage: 1.1+ MB

In [201]:
df['Return_Reason'].value_counts()

Return_Reason
Defective           1327
Wrong item          1258
Changed mind        1255
Not as described    1212
Name: count, dtype: int64

In [202]:
df['Return_Reason'].isnull().sum()

np.int64(4948)

Okay, so far I have observed is that we are predicting that will the product be returned by the customer based on the current information we have. Meaning, that the `Reason of Return` is something which is provided only if the product is returned.<br><br>
A little bit confusing, I know. We can collect this data for taking a look at the problems of the customers. Yes, we will use this for the predicting if the product will be returned by the customer or not. Since, this attribute us only present in the instances where the product is returned for sure, so it might make our model biased for this particular attribute, making it completely dependent on this faeture. So, we will remove this and use other features.

In [203]:
df.drop(["Return_Reason"], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Product_Price                 10000 non-null  float64
 1   Order_Quantity                10000 non-null  int64
 2   Return_Status                 10000 non-null  int64
 3   Days_to_Return                5052 non-null   float64
 4   User_Age                      10000 non-null  int64
 5   Payment_Method                10000 non-null  object
 6   Shipping_Method               10000 non-null  object
 7   Discount_Applied              10000 non-null  float64
 8   Product_Category_Books        10000 non-null  float64
 9   Product_Category_Clothing     10000 non-null  float64
 10  Product_Category_Electronics  10000 non-null  float64
 11  Product_Category_Home         10000 non-null  float64
 12  Product_Category_Toys         10000 non-null  float64
dtypes: float64(8), int64(3), object(2)
memory usage: 1015.8+ KB

In [204]:
df['Payment_Method'].value_counts()

Payment_Method
Gift Card      2537
Debit Card     2510
PayPal         2480
Credit Card    2473
Name: count, dtype: int64

In [205]:
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Payment_Method']]).toarray()
encoded

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [206]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoder_df

,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_Gift Card,Payment_Method_PayPal
0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0
...,...,...,...,...
9995,0.0,0.0,0.0,1.0
9996,0.0,1.0,0.0,0.0
9997,1.0,0.0,0.0,0.0
9998,0.0,0.0,1.0,0.0
9999,0.0,1.0,0.0,0.0

In [207]:
df = pd.concat([df, encoder_df], axis=1)
df.head(5)

,Product_Price,Order_Quantity,Return_Status,Days_to_Return,User_Age,Payment_Method,Shipping_Method,Discount_Applied,Product_Category_Books,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Product_Category_Toys,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_Gift Card,Payment_Method_PayPal
0,411.59,3,1,387.0,58,Debit Card,Next-Day,45.27,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,288.88,3,1,31.0,68,Credit Card,Express,47.79,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,390.03,5,0,NaN,22,Debit Card,Next-Day,26.64,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,401.09,3,0,NaN,40,PayPal,Next-Day,15.37,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,110.09,4,0,NaN,34,Gift Card,Standard,16.37,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

Another feature in the spotlight! `Days_to_Return`! This can also make our model biased that if this particular is present, then the product will be returned! Removing this can be much better for protecting the model from getting biased towards this feature.

In [208]:
df.drop(["Days_to_Return", "Payment_Method"], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Product_Price                 10000 non-null  float64
 1   Order_Quantity                10000 non-null  int64
 2   Return_Status                 10000 non-null  int64
 3   User_Age                      10000 non-null  int64
 4   Shipping_Method               10000 non-null  object
 5   Discount_Applied              10000 non-null  float64
 6   Product_Category_Books        10000 non-null  float64
 7   Product_Category_Clothing     10000 non-null  float64
 8   Product_Category_Electronics  10000 non-null  float64
 9   Product_Category_Home         10000 non-null  float64
 10  Product_Category_Toys         10000 non-null  float64
 11  Payment_Method_Credit Card    10000 non-null  float64
 12  Payment_Method_Debit Card     10000 non-null  float64
 13  Payment_Method_Gift Card      10000 non-null  float64
 14  Payment_Method_PayPal         10000 non-null  float64
dtypes: float64(11), int64(3), object(1)
memory usage: 1.1+ MB

In [209]:
df['Shipping_Method'].value_counts()

Shipping_Method
Next-Day    3394
Express     3306
Standard    3300
Name: count, dtype: int64

In [212]:
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Shipping_Method']]).toarray()
encoded

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [214]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
df = pd.concat([df, encoder_df], axis=1)
df.head(5)

,Product_Price,Order_Quantity,Return_Status,User_Age,Shipping_Method,Discount_Applied,Product_Category_Books,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Product_Category_Toys,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_Gift Card,Payment_Method_PayPal,Shipping_Method_Express,Shipping_Method_Next-Day,Shipping_Method_Standard
0,411.59,3,1,58,Next-Day,45.27,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,288.88,3,1,68,Express,47.79,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,390.03,5,0,22,Next-Day,26.64,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,401.09,3,0,40,Next-Day,15.37,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,110.09,4,0,34,Standard,16.37,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [215]:
df.drop(["Shipping_Method"], axis=1, inplace=True)
df.head(5)

,Product_Price,Order_Quantity,Return_Status,User_Age,Discount_Applied,Product_Category_Books,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,Product_Category_Toys,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_Gift Card,Payment_Method_PayPal,Shipping_Method_Express,Shipping_Method_Next-Day,Shipping_Method_Standard
0,411.59,3,1,58,45.27,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,288.88,3,1,68,47.79,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,390.03,5,0,22,26.64,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,401.09,3,0,40,15.37,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,110.09,4,0,34,16.37,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Product_Price                 10000 non-null  float64
 1   Order_Quantity                10000 non-null  int64
 2   Return_Status                 10000 non-null  int64
 3   User_Age                      10000 non-null  int64
 4   Discount_Applied              10000 non-null  float64
 5   Product_Category_Books        10000 non-null  float64
 6   Product_Category_Clothing     10000 non-null  float64
 7   Product_Category_Electronics  10000 non-null  float64
 8   Product_Category_Home         10000 non-null  float64
 9   Product_Category_Toys         10000 non-null  float64
 10  Payment_Method_Credit Card    10000 non-null  float64
 11  Payment_Method_Debit Card     10000 non-null  float64
 12  Payment_Method_Gift Card      10000 non-null  float64
 13  Payment_Method_PayPal         10000 non-null  float64
 14  Shipping_Method_Express       10000 non-null  float64
 15  Shipping_Method_Next-Day      10000 non-null  float64
 16  Shipping_Method_Standard      10000 non-null  float64
dtypes: float64(14), int64(3)
memory usage: 1.3 MB

In [217]:
df.to_csv("cleaned dataset.csv", index=False)